server:
    port: 8080

spring:
    application:
        name: board
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
        username: ${POSTGRES_USER:postgres}
        password: ${POSTGRES_PASSWORD:Post123321}
        driver-class-name: org.postgresql.Driver
    flyway:
        baseline-on-migrate: true
        schemas: board
    jpa:
        properties:
        hibernate:
            default_schema: board

management:
    endpoints:
        web:
            base-path: /board/actuator
            exposure:
                include: [ 'prometheus' ]

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
        defaultZone: http://${DISCOVERY_HOST}:8761/eureka/
