apiVersion: apps/v1
kind: Deployment
metadata:
  name: board
spec:
  selector:
    matchLabels:
      app: board
  replicas: 1
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
        - name: board
          image: femcdias/board:latest
          ports:
            - containerPort: 8080
          env:

            - name: DISCOVERY_HOST
              valueFrom:
                configMapKeyRef:
                  name: discovery-configmap
                  key: DISCOVERY_HOST

            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_HOST

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD

            - name: REDIS_HOST
              value: "redis-service"
  
            - name: REDIS_PORT
              value: "6379"